"""
Django settings for el_buen_precio project.

Generated by 'django-admin startproject' using Django 4.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
import dj_database_url
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

SECRET_KEY = os.environ.get('SECRET_KEY', default='your secret key')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = 'RENDER' not in os.environ

ALLOWED_HOSTS = ['*']

RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)
    
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'inicio_app',
    'administracion_app',
    'usuario_ventas_app',
    'bootstrap5',
    'django_template_maths',
    'sweetify',
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'administracion_app.middleware.BloquarRutasMiddleware',
    'usuario_ventas_app.middleware.BloquarRutasMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

ROOT_URLCONF = 'el_buen_precio.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'el_buen_precio.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        # Replace the connection string with the one provided by Azure
        default='mssql://root-analisis:F12345abc.@proyecto-analisis2.database.windows.net:1433/el_buen_preciodb?driver=ODBC+Driver+17+for+SQL+Server',
        conn_max_age=600,
        engine='mssql',
    )
}

"""
DATABASES = {
    'default': {
        'ENGINE': 'mssql',
        'NAME': 'el_buen_preciodb',
        'USER': 'root-analisis',
        'PASSWORD': 'F12345abc.',
        'HOST': 'proyecto-analisis2.database.windows.net',
        'PORT': '',

        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
            
        },
    },
}
"""

"""
#Local Config
DATABASES = {
    'default': {
        'ENGINE': 'mssql',
        'NAME': 'la_surtidora_buen_precio_A2',
        'USER': 'sa',
        'PASSWORD': '123456789',
        'HOST': 'localhost\SQLEXPRESS',
        'PORT': '',
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
        },
    },
}
"""

# Password validation



# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

""" LANGUAGE_CODE = 'es-ES'

USE_L10N = True

TIME_ZONE = 'America/Guatemala'

USE_I18N = True

USE_TZ = True

DEFAULT_CHARSET = 'utf-8' """

LANGUAGE_CODE = 'es-ES'

TIME_ZONE = 'America/Guatemala'

USE_L10N = False

#IME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/


STATIC_URL = '/static/'

if not DEBUG:
    # Tell Django to copy statics to the `staticfiles` directory
    # in your application directory on Render.
    STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

    # Turn on WhiteNoise storage backend that takes care of compressing static files
    # and creating unique names for each version so they can safely be cached forever.
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

print(BASE_DIR)
# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

"""
Nov 12 08:15:31 PM  ==> Cloning from https://github.com/George-MvQ/A2_tienda_el_buen_precio...
Nov 12 08:15:32 PM  ==> Checking out commit 7933fea2157164f91d7ea0a14a345c1163a06aec in branch main
Nov 12 08:15:35 PM  ==> Using Node version 14.17.0 (default)
Nov 12 08:15:35 PM  ==> Docs on specifying a Node version: https://render.com/docs/node-version
Nov 12 08:15:46 PM  ==> Using Python version 3.11.4 via environment variable PYTHON_VERSION
Nov 12 08:15:46 PM  ==> Docs on specifying a Python version: https://render.com/docs/python-version
Nov 12 08:15:49 PM  ==> Using Poetry version 1.1.14 (default)
Nov 12 08:15:49 PM  ==> Docs on specifying a Poetry version: https://render.com/docs/poetry-version
Nov 12 08:15:49 PM  ==> Running build command './build.sh'...
Nov 12 08:15:49 PM  ./build.sh: line 2: sudo: command not found
Nov 12 08:15:49 PM    % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Nov 12 08:15:49 PM                                   Dload  Upload   Total   Spent    Left  Speed
Nov 12 08:15:50 PM  
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   983  100   983    0     0   8936      0 --:--:-- --:--:-- --:--:--  8936
Nov 12 08:15:51 PM  Warning: apt-key output should not be parsed (stdout is not a terminal)
Nov 12 08:15:51 PM  E: This command can only be used by root.
Nov 12 08:15:51 PM  ./build.sh: line 4: /etc/apt/sources.list.d/mssql-release.list: Read-only file system
Nov 12 08:15:51 PM  ==> Build failed 😞
"""

