# Generated by Django 4.2.5 on 2023-09-29 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion_app', '0003_categorias'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id_caja', models.AutoField(db_column='ID_caja', primary_key=True, serialize=False)),
                ('anio', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='Anio', max_length=4)),
                ('mes', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='Mes', max_length=10)),
                ('total_gastos', models.DecimalField(db_column='Total_gastos', decimal_places=4, max_digits=19)),
                ('total_ingresos', models.DecimalField(db_column='Total_ingresos', decimal_places=4, max_digits=19)),
                ('total_caja', models.DecimalField(db_column='Total_caja', decimal_places=4, max_digits=19)),
            ],
            options={
                'db_table': 'Caja',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id_compra', models.BigAutoField(db_column='ID_compra', primary_key=True, serialize=False)),
                ('fecha_compra', models.DateField(blank=True, db_column='Fecha_compra', null=True)),
                ('observaciones', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='Observaciones', max_length=100, null=True)),
            ],
            options={
                'db_table': 'Compras',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id_detalle_compra', models.BigAutoField(db_column='ID_detalle_compra', primary_key=True, serialize=False)),
                ('descuentos', models.DecimalField(blank=True, db_column='Descuentos', decimal_places=4, max_digits=19, null=True)),
                ('cantidad_compra', models.IntegerField(db_column='Cantidad_compra')),
                ('precio_unitario_compra', models.DecimalField(decimal_places=4, max_digits=19)),
                ('precio_sugerido_venta', models.DecimalField(db_column='Precio_sugerido_venta', decimal_places=4, max_digits=19)),
                ('no_lote', models.IntegerField(db_column='No_lote')),
            ],
            options={
                'db_table': 'Detalle_compra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleListadoDePedidos',
            fields=[
                ('id_ls_detalle_producto', models.BigAutoField(db_column='ID_ls_detalle_producto', primary_key=True, serialize=False)),
                ('cantidad_a_comprar', models.IntegerField(db_column='Cantidad_a_comprar')),
            ],
            options={
                'db_table': 'Detalle_listado_de_pedidos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleVentas',
            fields=[
                ('id_detalle_venta', models.AutoField(db_column='ID_detalle_venta', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Detalle_ventas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id_empleado', models.AutoField(db_column='ID_empleado', primary_key=True, serialize=False)),
                ('primer_nombre', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='Primer_nombre', max_length=50)),
                ('segundo_nombre', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='Segundo_nombre', max_length=50)),
                ('otros_nombres', models.TextField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='Otros_nombres', null=True)),
                ('primer_apellido', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='Primer_apellido', max_length=50)),
                ('segundo_apellido', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='Segundo_apellido', max_length=50, null=True)),
                ('apellido_casada', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='Apellido_casada', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Empleados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id_inventario', models.AutoField(db_column='ID_inventario', primary_key=True, serialize=False)),
                ('fecha_ultima_salida', models.DateField(blank=True, db_column='Fecha_ultima_salida', null=True)),
                ('fecha_ultima_entrada', models.DateField(blank=True, db_column='Fecha_ultima_entrada', null=True)),
                ('total_stock', models.IntegerField(blank=True, db_column='Total_stock', null=True)),
            ],
            options={
                'db_table': 'Inventario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ListadoPedidos',
            fields=[
                ('id_listado', models.BigAutoField(db_column='ID_listado', primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateField(db_column='Fecha_creacion')),
                ('estado', models.BooleanField(db_column='Estado')),
            ],
            options={
                'db_table': 'Listado_pedidos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MetodosPago',
            fields=[
                ('id_metodo_pago', models.AutoField(db_column='ID_metodo_pago', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='Nombre', max_length=50, null=True)),
                ('descripcion', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='Descripcion', max_length=100, null=True)),
            ],
            options={
                'db_table': 'Metodos_pago',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MovimientoCaja',
            fields=[
                ('id_mov_caja', models.AutoField(db_column='ID_mov_caja', primary_key=True, serialize=False)),
                ('fecha', models.DateField(db_column='Fecha')),
                ('descripcion', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='Descripcion', max_length=50)),
                ('observaciones', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='Observaciones', max_length=150, null=True)),
                ('monto_total', models.DecimalField(db_column='Monto_total', decimal_places=4, max_digits=19)),
            ],
            options={
                'db_table': 'Movimiento_caja',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Movimientos',
            fields=[
                ('id_movimiento', models.AutoField(db_column='ID_movimiento', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='Nombre', max_length=50)),
            ],
            options={
                'db_table': 'Movimientos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Presentacion',
            fields=[
                ('id_presentacion', models.AutoField(db_column='ID_presentacion', primary_key=True, serialize=False)),
                ('nombre_presentacion', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='Nombre_presentacion', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Presentacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_productos', models.AutoField(db_column='ID_productos', primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='Nombre_producto', max_length=50)),
                ('descripcion', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='Descripcion', max_length=100, null=True)),
                ('codigo_barras', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='Codigo_barras', max_length=20, null=True)),
                ('tamanio', models.DecimalField(db_column='Tamanio', decimal_places=2, max_digits=4)),
                ('imagen', models.BinaryField(db_column='Imagen', max_length='max')),
                ('estado', models.BooleanField(db_column='Estado')),
            ],
            options={
                'db_table': 'Productos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id_proveedor', models.AutoField(db_column='ID_proveedor', primary_key=True, serialize=False)),
                ('nombre_vendedor', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='Nombre_vendedor', max_length=50, null=True)),
                ('telefono', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='Telefono', max_length=20, null=True)),
                ('estado', models.BooleanField(blank=True, db_column='Estado', null=True)),
                ('dia_visita', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='Dia_visita', max_length=25, null=True)),
                ('dia_entrega', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='Dia_entrega', max_length=25, null=True)),
                ('descripcion', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='Descripcion', max_length=100, null=True)),
            ],
            options={
                'db_table': 'Proveedores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Puestos',
            fields=[
                ('id_puestos', models.AutoField(db_column='ID_puestos', primary_key=True, serialize=False)),
                ('nombre_puesto', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='Nombre_puesto', max_length=25)),
                ('detalles', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='Detalles', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Puestos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UnidadesMedidas',
            fields=[
                ('id_medicion', models.AutoField(db_column='ID_medicion', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='Descripcion', max_length=10, null=True)),
                ('prefijo', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=6, null=True)),
            ],
            options={
                'db_table': 'Unidades_medidas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id_venta', models.BigAutoField(db_column='ID_venta', primary_key=True, serialize=False)),
                ('fecha_venta', models.DateField(blank=True, db_column='fecha_Venta', null=True)),
                ('total_monto_venta', models.DecimalField(blank=True, db_column='Total_monto_venta', decimal_places=4, max_digits=19, null=True)),
                ('total_monto_pago', models.DecimalField(blank=True, db_column='Total_monto_pago', decimal_places=4, max_digits=19, null=True)),
                ('descuento', models.DecimalField(blank=True, db_column='Descuento', decimal_places=4, max_digits=19, null=True)),
            ],
            options={
                'db_table': 'Ventas',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
    ]
