# Generated by Django 4.2.5 on 2023-10-09 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion_app', '0005_authuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marcas',
            options={'managed': True},
        ),
    ]
