# Generated by Django 4.2.5 on 2023-10-09 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion_app', '0006_alter_marcas_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marcas',
            options={'managed': False},
        ),
    ]
